### ISSUE TITLE
undefined reference to `sceSysconGetPommelVersion'

### ISSUE THREAD

**Issue by bmaupin** [pspdev/psplinkusb#7]
This fails to compile using https://github.com/pspdev/pspsdk with the following error:

```
$ podman run --rm -v "$PWD:/build" bmaupin/pspdev:gcc-4.6.4 make release
...
main.o: In function `initialise':
(.text+0x1b4): undefined reference to `sceSysconGetPommelVersion'
```

I don't even see `sceSysconGetPommelVersion` in https://github.com/pspdev/pspsdk/blob/master/src/kernel/pspsyscon.h

A workaround is to replace:

```c
        int t_result = sceSysconGetPommelVersion(&t_pommel);
```

with:

```c
        int t_result = sceSyscon_driver_E7E87741(&t_pommel);
```

in usbgdb/main.c

Thanks!

**Comment by 123survesh** [comment]
I got stuck with that part as well. Thanks for posting this issue. I replaced `sceSysconGetPommelVersion` with `sceSyscon_driver_E7E87741` as you said.

**Comment by Fighter19** [comment]
As someone already found out,
https://github.com/pspdev/pspsdk/pull/23
is required for the patch that is already merged to work.
(Meanwhile you can just use the workaround)

I expected both PRs to get merged at the same time, but forgot to mention, that they depend on each other.

**Comment by carstene1ns** [comment]
This one is finally fixed.
